### ISSUE TITLE
line detection checklist

### ISSUE THREAD

**Issue by JohnHeikens** [JohnHeikens/IntelliSkript#27]
- [ ] function detection
- [ ] skript-reflect java function call detection
- [ ] skript parse section detection
- [ ] event-value detection
- [ ] tyoe pattern detection (skript aliases)
